<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nom' => 'admin',
                'prenom' => NULL,
                'civilite' => NULL,
                'adresse' => NULL,
                'complement_adresse' => NULL,
                'code_postal' => NULL,
                'ville' => NULL,
                'pays' => NULL,
                'telephone1' => NULL,
                'telephone2' => NULL,
                'statut' => NULL,
                'siret' => NULL,
                'email' => 'admin@gmail.com',
                'email_perso' => NULL,
                'role' => 'admin',
                'demande_facture' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$dwJ3nLNI6yJz8NblWQggSecE9Rsyzcf09FcZ5yo1HVmf/GWTTE1je',
                'chiffre_affaire' => NULL,
                'commission' => NULL,
                'pack_actuel' => NULL,
                'nb_mois_pub_restant' => 12,
                'chiffre_affaire_sty' => 0.0,
                'remember_token' => 'cIrneExiNdAT4nEqyIfOY7rhZGEdR97X8mdXYptLuV2xKLz3khQLEWbvVXDY',
                'created_at' => '2019-10-14 08:31:19',
                'updated_at' => '2019-10-18 16:07:58',
                'chiffre_affaire' => 0,
            ),
            1 => 
            array (
                'id' => 11,
                'nom' => 'Bongo',
                'prenom' => 'Jean Philippe',
                'civilite' => 'M.',
                'adresse' => '5 rue des montains',
                'complement_adresse' => NULL,
                'code_postal' => '91260',
                'ville' => 'Juvisy-sur-orge',
                'pays' => 'France',
                'telephone1' => '0769191053',
                'telephone2' => NULL,
                'statut' => 'independant',
                'siret' => '14525252525',
                'email' => 'bongojeanphilippe@gmail.com',
                'email_perso' => 'bongojeanphilippe@gmail.com',
                'role' => 'mandataire',
                'demande_facture' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4P4hoKdRad7jQ4pjE6k2HuJ8rfdsFoDKd6jb57JWQY8Q8ohBkoqSm',
                'chiffre_affaire' => NULL,
                'commission' => 72.0,
                'pack_actuel' => 'starter',
                'nb_mois_pub_restant' => 12,
                'chiffre_affaire_sty' => 0.0,
                'remember_token' => 'PnkWtp7ObXgaf03qv5GkHBt3iDsgsvxWH6hIlwMNtXsetBs6wWA50wVh3KPL',
                'created_at' => '2019-10-17 12:34:37',
                'updated_at' => '2019-10-30 14:22:57',
                'chiffre_affaire' => 0,
            ),
            2 => 
            array (
                'id' => 12,
                'nom' => 'test',
                'prenom' => 'test',
                'civilite' => 'M.',
                'adresse' => '5 rue des claviers',
                'complement_adresse' => 'rr',
                'code_postal' => '14744',
                'ville' => 'martin',
                'pays' => 'France',
                'telephone1' => '0478524455',
                'telephone2' => NULL,
                'statut' => 'auto-entrepreneur',
                'siret' => '14525252525',
                'email' => 'test@gmail.com',
                'email_perso' => 'test@gmail.com',
                'role' => 'mandataire',
                'demande_facture' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$0KghbsU1hcOYhdzIqPSyTe81kBDuvrDsM6dlNEIdg0WVZoDnbCKK.',
                'chiffre_affaire' => NULL,
                'commission' => 65.0,
                'pack_actuel' => 'starter',
                'nb_mois_pub_restant' => 6,
                'chiffre_affaire_sty' => 0.0,
                'remember_token' => 'WunbJKjptOaZyQMqOC2IrJxxxqKCnWc8wK0Ysy85HPFnYndR8BGan7V4IO50',
                'created_at' => '2019-10-17 13:28:28',
                'updated_at' => '2019-10-17 16:02:49',
                'chiffre_affaire' => 200,
            ),
            3 => 
            array (
                'id' => 13,
                'nom' => 'alino',
                'prenom' => 'Alex',
                'civilite' => 'M.',
                'adresse' => '5 rue des claviers',
                'complement_adresse' => 'rr',
                'code_postal' => '14744',
                'ville' => 'martin',
                'pays' => 'France',
                'telephone1' => '0478524455',
                'telephone2' => NULL,
                'statut' => 'independant',
                'siret' => '14525 2525 25',
                'email' => 'alain@gmail.com',
                'email_perso' => 'alain@gmail.com',
                'role' => 'mandataire',
                'demande_facture' => 0,
                'email_verified_at' => NULL,
                'password' => NULL,
                'chiffre_affaire' => NULL,
                'commission' => NULL,
                'pack_actuel' => NULL,
                'nb_mois_pub_restant' => 12,
                'chiffre_affaire_sty' => 0.0,
                'remember_token' => NULL,
                'created_at' => '2019-10-28 08:35:54',
                'updated_at' => '2019-10-28 08:35:54',
                'chiffre_affaire' => 0,
            ),
            4 => 
            array (
                'id' => 14,
                'nom' => 'ggg',
                'prenom' => 'ggg',
                'civilite' => 'M.',
                'adresse' => '5 rue des claviers, rr',
                'complement_adresse' => 'rr',
                'code_postal' => '14744',
                'ville' => 'martin',
                'pays' => 'France',
                'telephone1' => '0478524455',
                'telephone2' => '0478524455',
                'statut' => 'independant',
                'siret' => '14525252525',
                'email' => 'green@gmail.com',
                'email_perso' => 'green@gmail.com',
                'role' => 'mandataire',
                'demande_facture' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$FlKlAOeeWaOm4DwMWfRb2uSVEZaxOKs/9v.Hvc9PbSySe83VbWZZq',
                'chiffre_affaire' => NULL,
                'commission' => 65.0,
                'pack_actuel' => 'starter',
                'nb_mois_pub_restant' => 12,
                'chiffre_affaire_sty' => 0.0,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 13:30:18',
                'updated_at' => '2019-10-30 13:55:44',
                'chiffre_affaire' => 0,
            ),
        ));
        
        
    }
}